name: CI - Build and Push Frontend Service

on:
  push:
    branches:
      - main

env:
  SERVICE: frontend-service
  IMAGE_SHA: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-service:${{ github.sha }}
  IMAGE_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-service:latest
  GITOPS_REPO: Tracel-web-project/Travel-gitOps
  GITOPS_DEPLOYMENT_PATH: apps/dev/frontend
  GITOPS_BRANCH_PREFIX: ci/update-frontend-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code
        run: |
          npm install
          npm run lint
                
      - name: Run Unit Tests
        run: |
          npm install
          npm test || true
          
      - name: SAST with CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          upload-sarif: false
          
      - name: SCA (Dependency Scan)
        run: |
          npm install -g npm-audit-ci
          npm-audit-ci --moderate || true
            

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_LATEST }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: gitops
          token: ${{ secrets.GITOPS_PAT }}

      - name: Update Kustomization
        run: |
          cd gitops/${{ env.GITOPS_DEPLOYMENT_PATH }}
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE }}=${{ env.IMAGE_SHA }}

      - name: Commit and Push changes
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b ${{ env.GITOPS_BRANCH_PREFIX }}-${{ github.sha }}
          git add .
          git commit -m "Update ${{ env.SERVICE }} image to ${{ env.IMAGE_SHA }}"
          git push origin HEAD
